extends: airbnb
installedESLint: true
plugins:
  - react
  - jsx-a11y
  - import
env:
  browser: true
rules:
  # don't complain about devDependencies in tests or webpack configs
  import/no-extraneous-dependencies:
    - 'error'
    - devDependencies:
      - '**/*.test.js'
      - 'webpack*'
